version: "3.8"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  rate-limiter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rate-limiter
    ports:
      - "8090:8090"
    environment:
      - REDIS_HOST=redis:6379
      - DEFAULT_LIMIT=10
      - DEFAULT_TTL=60
    depends_on:
      - redis

volumes:
  redis-data:
